post:
  tags:
   - Authentication
  parameters:
    - $ref: '@provider@.yaml'
  summary: "Authentication to provider"
  requestBody:
    required: true
    content:
      application/json:
        schema:
          properties:
            login:
              type: "string"
              example: "admin"
            password:
              type: "string"
              example: "centreon"
  responses:
    "200":
      description: "OK"
      content:
        application/json:
          schema:
            properties:
              redirect_uri:
                type: string
                example: "/centreon/main.php?p=50113&o=ldap"
    '302':
      description: "Found"