openapi: 3.0.1
info:
  title: Centreon Web RestAPI
  description: |
    # New features
    + Added real-time monitoring for hosts and services
    + Added acknowledgement for hosts and services
    + Added downtimes for hosts and services
    + Added the list of monitoring server configurations
    + Added the proxy configuration
    # Information
    All dates are in **ISO 8601** format
    # Authentication
    There are two modes of authentication:
    * By token: after identification with your login credentials
    * By cookie: by reusing a valid session ID
  x-logo:
    url: ./centreon-logo.png
  contact:
    name: Centreon
    url: 'https://www.centreon.com'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  version: "22.10"
externalDocs:
  description: You can contact us on our community Slack
  url: 'https://centreon.slack.com/messages/CCRGLQSE5'
servers:
  - url: '{protocol}://{server}:{port}/centreon/api/{version}'
    variables:
      protocol:
        enum:
          - http
          - https
        default: http
        description: "HTTP schema"
      server:
        default: localhost
        description: "IP address or hostname of Centreon server"
      port:
        default: '80'
        description: "Port used by HTTP server"
      version:
        default: v22.10
        description: "Version of the API"
tags:
  - name: Acknowledgement
  - name: Administration
  - name: Authentication
    description: "Login and logout endpoints to retrieve authentication token"
  - name: Downtime
  - name: Gorgone
  - name: Host
  - name: Host category
  - name: Host group
  - name: Meta service
  - name: Host severity
  - name: Host template
  - name: Monitoring server
  - name: Proxy
  - name: Service
  - name: Service group
  - name: Service category
  - name: Topology
paths:
  /v22.10/monitoring/services/categories:
    $ref: "./v22.10/Monitoring/service_categories.yaml"