services:

    CentreonDev\:
        resource: '../../../src/CentreonDev/*'

    Centreon\Infrastructure\DatabaseConnection:
        class: CentreonDev\DataCollector\TraceablePDO
        arguments:
            $host: '%database_host%'
            $port: '%database_port%'
            $basename: '%database_db%'
            $login: '%database_user%'
            $password: '%database_password%'
        calls:
            - method: setCentreonDbName
              arguments: ['%database_db%']
            - method: setStorageDbName
              arguments: ['%database_dbstg%']

    pdo_data_collector:
        class: CentreonDev\DataCollector\PdoDataCollector
        arguments: ['@Centreon\Infrastructure\DatabaseConnection']
        public: false
        tags:
            -
                name: data_collector
                id: 'pdo_data_collector'
                template: '@data_collector/db.html.twig'
