---
centreon.severity.realtime.findHostSeverities:
    methods: "GET"
    path: "/monitoring/hosts/severities"
    controller: >-
        Core\Severity\RealTime\Infrastructure\API\FindHostSeverity\FindHostSeverityController
    condition: "request.attributes.get('version') >= 22.04"

centreon.severity.realtime.findServiceSeverities:
    methods: "GET"
    path: "/monitoring/services/severities"
    controller: >-
        Core\Severity\RealTime\Infrastructure\API\FindServiceSeverity\FindServiceSeverityController
    condition: "request.attributes.get('version') >= 22.04"
